### ISSUE TITLE
FindByXPath gives error

### ISSUE THREAD

**Issue by marcelloh** [sclevine/agouti#139]
According to the documentation:
> FindByXPath finds exactly one element by XPath selector.

but when I do:
```
//*[contains(@class, "mdl-menu")]
test := AgoutiPage.FindByXPath(findText)
```
It tells me that: failed to select element from selection 'XPath: //*[contains(@class, "mdl-menu")] [single]': ambiguous find

I know it occurs more times in the html I'm trying to investigate

**Comment by rNavarrete** [comment]
My first guess would be that there are other items on the page with the same class, since it is claiming an ambiguous find.

**Comment by marcelloh** [comment]
That is completely true, the page has more of the same class.
But as the documentation says: FindByXpath find one element, I think it is not working.
(classes can occur more than one in a HTML page, even id's can if the programmer was sloppy)
or.. perhaps we need a FindElementsByXpath, which could return slices.

**Comment by sclevine** [comment]
All of the `Find` methods intentionally fail when more than one element that matches the selection is present. You can use `AllByXPath` or `FirstByXPath` if you don't need this behavior.

**Comment by GiuseC** [comment]
Hello,

Would it be possible refactor the function `FindByClass` in order to return a list of `*Selection`, in this way I would be able to select different element that got the same class name. 
With the current approach I do not understand how can I interact with an element that has common class name and it is not the first in order of appearance (behaviour that I found very common in all the web app that I tested)

Thank you

**Comment by GiuseC** [comment]
Actually never mind I found I can achieve it with the function `AllByClass`
