### ISSUE TITLE
Request: Appium support

### ISSUE THREAD

**Issue by abourget** [sclevine/agouti#33]
I will need Appium extensions support.. I'm willing to start contributing. Is there a way to layout the code that you'd prefer ?

**Comment by sclevine** [comment]
This sounds great! I would create a separate `appium` package that is similar to the `api` package. It should provide `appium.Client` that depends on the same `session.Session` that `api.Client` depends on. I would expect the `appium.Client` to conform to the Appium WebDriver extensions API in the same way that `api.Client` conforms to the WebDriver Wire Protocol.

Let me know if you need any help!

**Comment by abourget** [comment]
wouldn't it be easier if we simply had a few more commands on the current models ?  like `FindA11y()` beside `FindText()` ..  just poking around right now.. I'll be diving into that in the next two weeks or so.

**Comment by sclevine** [comment]
What would `FindA11y` do, and where would you put it? Also, we don't have a function or method called `FindText()` in any package.

Sorry if I didn't provide enough detail. I was describing where I would expect the interface for the Appium WebDriver API to be implemented. `page.Page` and `selection.Selection` could certainly take an `appium.Client` as a dependency (just as they currently depend on `api.Client`) and provide extra methods that throw errors without Appium. You may want to create a new interface like `core.AppiumPage` so that non-Appium users don't have access to those methods.

If the user-level Appium methods won't depend on any of the other `page.Page` or `selection.Selection` methods, the Appium page and selection could live separately from `page.Page` and `selection.Selection` and be merged into `core.userPage` and `core.userSelection` as anonymous members.

**Comment by abourget** [comment]
heehee :) `FindByLabel()` I mean... `FindByA11y` would find by accessibility ID, I guess it could live near `FindByLabel()` and friends.  I'll get back to you when I put my head into this more seriously.

**Comment by abourget** [comment]
hey Stephen, I'm putting my head into this now.  Would we meet on IRC or at some determined time to chat about the design of that integration ?  I'll have a week or two to tackle that.. and I'll be a great joy to contribute to the agouti project!

**Comment by sclevine** [comment]
Hi @abourget, I would be happy to chat about this. I'll put an IRC channel in README.md, if that's your preferred method of communication. What times work for you? I could make myself available today around 8pm PST.

There have been quite a few architectural changes since this issue was opened. Here are some initial thoughts around what Appium support might look like:

User-level:
- Lives in `github.com/sclevine/agouti/appium`
- Provides an `appium.Page` struct that embeds `agouti.Page` and has an `extensions` field (see below)
- Provides an `appium.Selection` struct that embeds `agouti.Selection` and has an `extensions` field

WebDriver-level:
- Lives in `github.com/sclevine/agouti/appium/extensions`
- Provides an `extensions.Client` that has a `Session` field that holds an `api.Session`
- Extensions can call `client.Session.Send()` to make HTTP calls to the Appium server.

Integration:
- To build a new `appium.Page`:
   - Build an `agouti.Page` with `agouti.NewPage()`
   - Build an `extensions.Client` using the session from `agouti.Page#Session()`
   - Build an `appium.Page` by embedding the `agouti.Page` and setting `extensions` to the `extensions.Client`
- Building a new `appium.Selection` would be similar. Implement your own `selectable` struct that returns `appium.Selection`s instead of `agouti.Selection`s from its finder methods.
- Not sure what to do about integration tests. Can the Appium server control a regular browser without communicating with any external services? If so, they could live `github.com/sclevine/agouti/integration`, perhaps in a file called `appium_test.go`.

Finally:
- Let the Appium people know about this, and get Agouti listed here: http://appium.io/downloads

**Comment by abourget** [comment]
Are you around ? We can go on freenode on some random channel.

**Comment by abourget** [comment]
I'm looking at the `options.go` file.. and looking at the `Option` func, and I don't understand the usage of the Option function, etc.. especially not why it would be exposed publicly?

That func receives a `*config` pointer on which external libs can't even modify anything, is there a way we can simplify that ?

I'm asking because I get to a point where I need to pass in that `Option` thing when creating a `NewDevice()`..

**Comment by abourget** [comment]
why not simply have an `Option` struct on which we can leave certain fields blank ?  or, even better, remove it altogether ?  upon `NewWebDriver`, the only place the `.timeout` prop is read, we could simply tweak the `.Timeout` attribute afterwards.   Calls to `NewPage` only use the `desired` props from the Option, so why bother supporting all options at both places, when they aren't used at both places?

**Comment by abourget** [comment]
right, so `Option` seems to try to be generic, but one of its options is only used at the WebDriver level, and the other option is only used at the Page level.

Could we simplify that ?

**Comment by abourget** [comment]
for the timeout thing, it'd be better to have WebDriver.SetTimeout(string) and accept any `time.ParseDuration()` formatted string, or even an `interface{}` taking either a string or a `time.Duration`.

**Comment by abourget** [comment]
but I do see the point of future-proofing the API.. I guess it should stay as it is.

**Comment by abourget** [comment]
See: https://github.com/abourget/agouti/commit/ddffbbef2601bd67cca7801cc282be23fdcd9c9c to follow up on the "Options" disucssion.

**Comment by abourget** [comment]
That would be a first draft of how we lay things out, with the new Options model: https://github.com/abourget/agouti/commit/655a70a0eec39b7ee3c650f45eba37564fff5bf3

I understand this breaks retro compatibility.. how best handle that ?

**Comment by abourget** [comment]
here is the first draft of the Appium implementation, comments welcome:

https://github.com/abourget/agouti/commit/e00217daf7ff98c92d22628728b28d1d73980646

**Comment by sclevine** [comment]
Hi @abourget,

I also posted this on abouget@ddffbbe, but [see here](http://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis) for some of the design justification.

I would like to keep the Agouti `Option`s the way they are now. I don't want to break the existing API, and the current implementation is flexible and future-proof. They also allow `Option`s that are set on a `WebDriver` to apply to new `Page`s. You should rebase against master, as you don't have some of these changes on your branch.

I would provide an `appium.Option` that stores a corresponding (or new) `agouti.Option` in its `*config`. Does that cover your use case?

**Comment by sclevine** [comment]
Hi @abourget,

I pushed a few design ideas to a branch. See 0b204743ccbbc475b59622665534f9e6648256bb.

I threw this together pretty quickly. It's not intended to be functional, just to give you some idea of what I'm thinking. Let me know if it helps!

-Stephen

**Comment by abourget** [comment]
I,m looking at `api.session.go:Session.GetElements` and it looks prreeettty much exactly like `api.element:Element.GetElements` .. same with his other `Get..` friends.  Could we merge those together ? or could the Element's method use the Session's ?

**Comment by sclevine** [comment]
`GetElement` and `GetElements` on `api.Element` are similar to their `api.Session` counterparts, but they call out to different endpoints. While it's certainly possible for them to share logic, both of those methods are very short and could eventually diverge, so I don't see a great reason to do that.

**Comment by abourget** [comment]
oh right, Element calls subelements, I see.

**Comment by abourget** [comment]
not sure where to split "Mobile" and "Appium".. some of the features are mobile centric (and are being developed in a `Mobile JSON Wire Protocol`), some things are specific to Appium..

I'll start with something crude, and we can rename as distinctions become clearer.

**Comment by sclevine** [comment]
That's fine, as long as the `mobile` package ends up looking like the `api` package (as a raw implementation of the protocol with as little logic as possible). These packages (once documented) could be valuable for other people who want to use those protocols.

I came up with a solution to the `Selection` issues, fixed some tests, and did a little refactoring [here](https://github.com/abourget/agouti/compare/master...sclevine:abourget). This hides the `target.Selectors` by casting them to an opaque type. Packages outside of `agouti` won't be able to import `agouti/internal/target`, and therefore can't cast them back.

**Comment by sclevine** [comment]
Worked out a few more things: e349ec788d8e7f053d8e66bf6fc666efce6b433f
This should be reflected in the diffs I posted above.
Let me know if this helps!

**Comment by sclevine** [comment]
Rebased that branch against master [here](https://github.com/sclevine/agouti/tree/abourget-rebased).

**Comment by sclevine** [comment]
@abourget,

In case this affects what your working on, I'm planning on implementing `agouti.Cursor` soon. This object will be returned by `page.Cursor()` and store a position that gets set by `cursor.MoveToPosition(x, y int)` or `cursor.MoveToSelection(selection *Selection)`. I may also implement `selection.Cursor()`, which returns an `agouti.Cursor` that starts positioned on the selection. Every method on an `agouti.Cursor` will move the "mouse" to the stored position of the individual `agouti.Cursor` before executing (if necessary). All of the `/session/:sessionID/touch/*` methods (as well as some mouse-related endpoints like `buttondown` will be accessible through a `*agouti.Cursor`.

**Comment by abourget** [comment]
Closing this, follow up in https://github.com/sclevine/agouti/pull/44
