### ISSUE TITLE
First("not_there").Visible() generates a bad protocol request

### ISSUE THREAD

**Issue by joelgwebber** [sclevine/agouti#58]
This manifests as:

`failed to determine whether selection 'CSS: not_there [0]' is visible: request unsuccessful: error parsing response: invalid character 'u' looking for beginning of value`

The actual value it was trying to parse is:

`unknown command: session/[garble]/element/displayed`

Which appears to be caused by the use of `path.Join()` in `api/element.go`. Specifically, when an indexed selector matches nothing, you get an `Element.ID == ""`. This generates a Selenium request of the form `"[...]/element/displayed"` rather than `"[...]/element//displayed"`. The latter won't work either, but at least Selenium doesn't choke on it, generating a non-JSON response.

---

The second part, of which I'm a bit less sure, is why it's possible to get an `Element.ID == ""` in the first place. This doesn't seem to happen with non-indexed selectors (e.g., `All("not_there").Visible()`) -- this generates the more sane response `failed to select elements from selection 'CSS: not_there': no elements found`. I'm still trying to make sense of precisely how this should work, but I suspect it shouldn't be generating element instances without their IDs set.

**Comment by joelgwebber** [comment]
One question, related to a possibly-erroneous assumption on my part: Should it be possible to make calls like `First("...").Visible()` without getting an error response in the case when an element's not been added to the DOM yet? I would assume that this would simply return `false` if there's no other error communicating with Selenium, as it's simply not there yet. But I may be misunderstanding the intent of the `Visible()` method -- is it only intended to be used on elements that are definitely attached?

**Comment by sclevine** [comment]
Hi @joelgwebber, thanks for the report!

The intent of the `Visible()` function is to return whether or not an existing element is visible on the page. It is supposed to return an error when an element does not exist. You're probably looking for the selection `Count()` function. If you use the `matchers` package, check out the `BeFound` matcher.

As for the inappropriate error message, I'm fairly sure that this is a case of Selenium not properly conforming to the [WebDriver Wire Protocol](https://code.google.com/p/selenium/wiki/JsonWireProtocol#/session/:sessionId/element). For efficiency, we special-case the situation where you want to retrieve the first element out of a selection by using the `/session/:sessionID/element` or `/session/:sessionID/element/:elementID/element` endpoint instead of the `/session/:sessionID/elements` or `/session/:sessionID/element/:elementID/elements` endpoint. These endpoints are supposed to instruct the WebDriver to search until it finds the first occurrence of an element, and return either than element or an error if that element does not exist. That's why we don't check the element returned by `GetElement` [here](https://github.com/sclevine/agouti/blob/master/internal/element/repository.go#L119). I suspect that Selenium is returning an empty element instead of an error.

If you can't confirm whether this is the case or not, I'll try to find some time later this week to test it out. Could you provide me with your Selenium version?

Thanks!
Stephen

**Comment by joelgwebber** [comment]
Thanks for the detailed followup. 

It may well be the case that the host is responding to the malformed URLs caused by the `path.Join()` issue with an incorrect response ("unknown command: session/[garble]/element/displayed" is certainly not JSON!). However, when the element is absent, and the request URL isn't malformed, the error that actually comes back is of the following form (which agouti fails to parse in `bus/client.go/Send()`, because it's expecting `value` to be `bool`):

    { "sessionId":"c910a87e9ff52ac8ac8d8696b509ce99",
      "status":10,
      "value": {
        "message": "stale element reference: element is not attached to the page document [...]"
      }
    }

This is being caused by an empty `Element.ID`, which itself is being triggered by the element being absent from the DOM. So far, this fits the scenario you've described, so I changed my test framework to ensure that it always checks `Count()` before `Visible()` (our app does a lot of DOM manipulation, so most tests want to perform some operation, then wait for a specific element to be both attached and visible).

Here's the rub, though. Unless I'm missing something, there appears to be a race condition here. After making this change, most of the errors went away. But in "wait for an element to be hidden" case, I'm still sometimes seeing errors. The following is a stripped-down sketch of the code:

    sel := page.First(selector)
    count, err := sel.Count()
    if count > 0 {
      visible, err := sel.Visible()
    }

As far as I can tell, it's possible for the element referred to by the selector to become stale between the calls to Count() and Visible(), if it's removed from the DOM at just the right time. I'm still knee-deep debugging the code, but it certainly looks like this is happening (it reliably hits the `Element.ID == ""` case in my test code in this case).

It may be that I'm misunderstanding how `Count()` and `Visible()` are meant to be used in this case. If so, please accept my thanks for allowing a bug-report to turn into stupid-user education :) At present, though, I have tests passing by ignoring errors, which seems sub-optimal.

Oh, and just in case it's helpful:

    (Session info: chrome=44.0.2403.157)
    (Driver info: chromedriver=2.14.313457 (3d645c400edf2e2c500566c9aa096063e707c9cf),
     platform=Mac OS X 10.10.4 x86_64)

**Comment by sclevine** [comment]
Again, the error is actually higher up the chain, when the element ID is retrieved. You should never end up with an empty `Element.ID`. I suspect the `*/element` endpoint call (which happens before the `*/element/:elementID/displayed` endpoint call) is returning either an empty element, or an error that happens to parse into an empty element (like the error you posted above).

I noticed that you're running ChromeDriver directly instead of Selenium. I wonder if ChromeDriver is responding to the `*/element` endpoint request with 2xx response formatted similarly to the error you posted above. This would get unmarshalled into an empty `Element`. Can you see if you still have this problem in Selenium?

Finally, can you clarify your use case? Are you trying to test that an element first becomes invisible, and then is removed from the DOM entirely?

`Count()` and `Visible()` are pretty straightforward. `Count()` returns the number of elements matching a selector (which is lazily evaluated when `Count()` is run). `Visible()` returns whether the elements matched by the selector are all visible, and returns an error if no elements match the selector.

**Comment by joelgwebber** [comment]
Right, that all makes sense -- it's possible that Chromedriver isn't following the spec precisely when the .../element/displayed endpoint is incorrectly called. I'm running Chromedriver directly because it simplifies things for our local builds. I'm not all that concerned about the broken error message -- just thought you might want to know about it.

My actual use case is that I'm trying to write a utility method that waits for an element to be either removed from the dom, or hidden. Our app has plenty of both cases, and it makes it a lot easier to write tests if you don't have to be concerned with precisely _how_ an element becomes invisible (that's just an implementation detail, and sometimes changes). The inner loop looks roughly like this:

    // Must return false when the element becomes either removed or hidden.
    func testVisibility(selector string) bool {
      sel := page.First(selector)
      count, err := sel.Count()
      if count == 0 {
        return false
      }
      visible, err := sel.Visible() // err comes back non-nil in some cases; possibly a race with Count()
      return visible
    }

It _appears_ that there are cases where `Count()` returns 1, presumably because the element is not yet removed, then `Visible()` returns an error because it got removed in the interim. But because this function doesn't actually know whether the element's ever going to be removed (again, it might be either removed or hidden, depending upon implementation details), it still has to call `Visible()` in the second step.

If there's a better approach to solving this problem, I'm very much open to ideas. And thanks again for taking the time to follow up on this -- I know supporting open-source projects is often a thankless task.

**Comment by joelgwebber** [comment]
Minor note about the error issue -- IIRC, it was being triggered by the call to Visible(), which has to get an Element from the selector before calling the /element/id/displayed endpoint. In case that's helpful.

**Comment by sclevine** [comment]
Again, the error returned by the `*/element/:elementID/displayed` endpoint is not relevant. It's the non-standard error (or lack of error) returned by the `*/element` endpoint that is causing the issue. I think that's what your second comment says. I'll look into this when I have a chance.

There are a few ways you could use Agouti to address your use case. One way would be to parse the error returned by `Visible` and look for the string `no elements found`. (Adding typed errors for things like this is on my To-Do list.) Here's an example:
```go
func testVisibility(selector string) (bool, error) {
   visible, err := page.First(selector).Visible()
   if err != nil {
      if err.Error() == "no elements found" {
         return false, nil
      }
      return false, err
   }
   return visible, nil
}

Hope this helps!
-Stephen

**Comment by joelgwebber** [comment]
Thanks, I think I'll just go with the error text hack for now -- I was just surprised that there was no natural route for avoiding this race condition (though to be fair, this seems more a selenium design issue than anything to do with agouti specifically). Typed errors would be very useful indeed, and I'll update our own test code once that becomes available.

I'll also go ahead and close this ticket. Thanks again for taking the time to talk this through.
