### ISSUE TITLE
Option or Capability to specify the proxy that PhantomJS should use

### ISSUE THREAD

**Issue by the-shank** [sclevine/agouti#70]
I am unable to find a way to set the proxy and the proxy authentication that PhantomJS should use.

For example the way to start phantomjs with the proxy and authentication information, directly from the command line is
`phantomjs --proxy=xx.xx.xx.xx --proxy-auth=user:password`

How can I do this for the `agouti.PhantomJS()` driver?

**Comment by ZeuCxb** [comment]
I`m with the same problem.

**Comment by sclevine** [comment]
I would be happy to accept a tested PR that introduces an `agouti.Proxy` function returning an `agouti.Option` that could be used by the webdriver functions in `agouti.go`.

Otherwise, it's easy to write your own custom `agouti.PhantomJS` function. The individual webdriver methods are just wrappers for `agouti.NewWebDriver`.

Example:
```go
func PhantomJSWithProxy(proxy, proxyAuth string, options ...Option) *agouti.WebDriver {
	command := []string{"phantomjs",
		"--webdriver={{.Address}}",
		"--proxy="+proxy, "--proxy-auth="+proxyAuth,
	}
	return NewWebDriver("http://{{.Address}}", command, options...)
}
```

**Comment by sclevine** [comment]
Closing this for now. Happy to accept a PR.
