### ISSUE TITLE
selectable.First().Count() return 1 even if no elements matched

### ISSUE THREAD

**Issue by lajonat** [sclevine/agouti#89]
Hey,
I'm using ChromeDriver, and trying to navigate some pages.
Using this code:
`
elem := page.FirstByXPath("//NotExisting")

n,r := elem.Count()
`
If the page I'm looking at doesn't have any NotExisting element, I would not get any error (r=nil), and n=1.
However, if I try to do anything with elem, I get an error  such as this:

> request unsuccessful: unknown command: session/086126d24691cbade922d1eade91f5d3/element/text

This behavior is on all the "First" methods. Interestingly, if using:
`
elem := page.AllByXPath("//NotExisting")

n,r := elem.Count()
`
the result is as expected, n=0.

Maybe I'm missing something, but I can't really know if I found a matching element if using this method.

**Comment by sclevine** [comment]
This is because of an optimization made for selecting the first element [here](https://github.com/sclevine/agouti/blob/master/internal/element/repository.go#L119).
We use the `:elementID/element` or `:sessionID/element` endpoint (see [here](https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#sessionsessionidelement)) to get the first matching element for the selector. This is faster than getting all matching elements with the `/elements` endpoints. The `/element` endpoints are supposed to return an error when no element is found, but they appear not to return an error in your case.

Can you demonstrate that this happens for other WebDrivers? If so, I'd consider removing the optimization, but if not, I would prefer this to be a bug report for ChromeDriver.

**Comment by lajonat** [comment]
OK, so apparently this is a bug in ChromeDriver.
Took the same code, substituted the driver with PhatomJS and it worked as expected:
When calling Count() the count is 0, and the error is "request unsuccessful: Unable to find element with xpath"
Thanks.
