### ISSUE TITLE
Make Page struct exportable (being able to create a custom Page object)

### ISSUE THREAD

**Issue by alex-kovoy** [sclevine/agouti#91]
Hi,

  I am trying to extend Page logic to add an ability to join an **existing** session (session ID). It would help me to avoid 'sign-in' steps during debug/development.

 Below non-exportable 'selectable' is what makes it complicated. Do you think it makes sense to export so it's possible to create a custom Page object? I am new to golang so if there is a better way to achieve my goal please let me know :-) Thank you guys!

type Page struct {
	selectable
	logs map[string][]Log
}

**Comment by sclevine** [comment]
Hi @alex-kovoy,

Interesting use case. You would need to expose more than just `agouti.selectable` to accomplish this -- you'll need to make a custom [bus.Client](https://github.com/sclevine/agouti/blob/master/api/internal/bus/client.go) without access to that package (due to the `internal` path).

Instead, I would happily accept a PR that added an `api.New()` method [here](https://github.com/sclevine/agouti/blob/master/api/session.go#L19) that created a `bus.Client` manually given an existing session URL.

**Comment by alex-kovoy** [comment]
I can create bus.Client and Session without api modifications:

	busClient := &Client{sessionURL, http.DefaultClient}
	session := &api.Session{busClient}

What's missing is basically the Page itself which has non-exportable props. What if I add 'Join' method in [here](https://github.com/sclevine/agouti/blob/master/page.go#L42)? It would then accept an existing session URL, httpClient and return a Page?

**Comment by sclevine** [comment]
An `api.New()` method and an `agouti.JoinPage()` method would be acceptable, but you won't be able to create the `bus.Client` outside of the `api` package because it's scoped under an `/internal/` path. See [here](https://golang.org/s/go14internal).

**Comment by alex-kovoy** [comment]
I've created a PR. Please let me know if anything is missing.
